version: '3'
services:

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=fraud_detection_db
      - MYSQL_USER=fraud_detection_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} # this should live in a env var
    volumes:
      - "./../db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
    ports:
      - "3307:3307"
      - "33061:33061"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

  web:
    container_name: web
    depends_on:
      - db
    build:
      context: "."
      dockerfile: "dockerfile-web"
    ports:
      - "8080:8080"
    command: ['catalina.sh', 'run']

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      # KAFKA_CREATE_TOPICS: "cars-data"

  jobmanager:
    image: apache/flink:1.18-java17
    container_name: flink-jobmanager
    command:
      - jobmanager
      - flink run -d -c "it.unipi.dsmt.Main" job/fraud-detector-1.0-jar-with-dependencies.jar
    ports:
      - "8081:8081"  # Flink Web UI port
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./target/fraud-detector-1.0-jar-with-dependencies.jar:/opt/flink/job/fraud-detector-1.0-jar-with-dependencies.jar


  taskmanager:
    image: apache/flink:1.18.0-java17
    container_name: flink-taskmanager-1
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

